### ISSUE TITLE
[Android] Trying to retrieve AdvertiserId on UI thread

### ISSUE THREAD

**Issue by tomaszpolanski** [adjust/flutter_sdk#54]
Version `4.29.0` introduced getting AdvertiserId on UI thread and it gives now a warning:

```
D/Adjust  ( 5881): GoogleAdId being read in the foreground
I/flutter ( 5881): Report log: Uncaught error: MissingPluginException(No implementation found for method getIdfa on channel com.adjust.sdk/api)
I/flutter ( 5881): Error: MissingPluginException(No implementation found for method getIdfa on channel com.adjust.sdk/api)
I/flutter ( 5881): StackTrace: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
I/flutter ( 5881): <asynchronous suspension>
I/flutter ( 5881): #1      Adjust.getIdfa (package:adjust_sdk/adjust.dart:85:26)
I/flutter ( 5881): <asynchronous suspension>
I/flutter ( 5881): 
I/flutter ( 5881): Message: null
I/flutter ( 5881): 
D/Adjust  ( 5881): GoogleAdId read 395164ba-2e46-452e-89f2-c4dc430c04f8
I/flutter ( 5881): Report log: Caught error: MissingPluginException(No implementation found for method getIdfa on channel com.adjust.sdk/api)
I/flutter ( 5881): Error: MissingPluginException(No implementation found for method getIdfa on channel com.adjust.sdk/api)
I/flutter ( 5881): StackTrace: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
I/flutter ( 5881): <asynchronous suspension>
I/flutter ( 5881): #1      Adjust.getIdfa (package:adjust_sdk/adjust.dart:85:26)
I/flutter ( 5881): <asynchronous suspension>
I/flutter ( 5881): 
I/flutter ( 5881): Message: Could not fetch AdvertiserId
```

This message did not appear in `4.28.0`

**Comment by uerceg** [comment]
Interesting. Thanks for reporting this @tomaszpolanski. We'll check it out and keep you posted.

**Comment by tomaszpolanski** [comment]
@uerceg Any updates on this issue? Still on `4.29` I cannot get ad id but on `4.28` I can

**Comment by uerceg** [comment]
Hi @tomaszpolanski 

Sorry for delay on this one. Hm. 🤔  Actually we gave this a shot and failed to reproduce on our end. Can you give our example app from the repo a shot (latest state of `flutter_sdk:master` branch) and let us know if you're seeing the same thing in there as well? With trying that app on our end, we're getting :

**iOS**
- `Adjust.getGoogleAdId()` executed first
- `Adjust.getIdfa()` afterwards

```
2021-09-23 00:44:36.337435+0200 Runner[980:38315] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(non_existing_method, getGoogleAdId not available for iOS platform, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
<asynchronous suspension>
#2      Adjust.getGoogleAdId (package:adjust_sdk/adjust.dart:95)
<asynchronous suspension>
2021-09-23 00:44:46.616617+0200 Runner[980:38315] flutter: Received IDFA: 95C74164-4DE0-4389-A761-4A4EF076FE63
```

**Android**
- `Adjust.getIdfa()` executed first
- `Adjust.getGoogleAdId()` afterwards

```
2021-09-23 00:45:55.932 3440-3631/com.adjust.examples E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getIdfa on channel com.adjust.sdk/api)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
    <asynchronous suspension>
    #1      Adjust.getIdfa (package:adjust_sdk/adjust.dart:85:26)
    <asynchronous suspension>
2021-09-23 00:45:59.985 3440-3440/com.adjust.examples D/Adjust: GoogleAdId being read in the foreground
2021-09-23 00:46:00.021 3440-3623/com.adjust.examples D/Adjust: GoogleAdId read 58df3b1f-33d0-4061-a976-b2af929517ca
2021-09-23 00:46:00.024 3440-3631/com.adjust.examples I/flutter: Received Google Advertising Id: 58df3b1f-33d0-4061-a976-b2af929517ca
```

In case things in example app end up working for you, wondering what might be different in setup on your and our end.

**Comment by tomaszpolanski** [comment]
Hey, sure. Will try to reproduce it with a sample app
