### ISSUE TITLE
Crashed on Android devices

### ISSUE THREAD

**Issue by averinuv** [adjust/flutter_sdk#73]
After adding sdk giving below error. version 4.29.1

Crashlytics log:
```
Fatal Exception: java.lang.IllegalAccessError: Illegal class access: 'androidx.room.h' attempting to access 'androidx.work.impl.WorkDatabase_Impl$a' (declaration of 'androidx.room.h' appears in base.apk)
       at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:97)
       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:177)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:416)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:145)
       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:106)
       at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)
       at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281)
       at androidx.work.impl.model.SystemIdInfoDao_Impl.getWorkSpecIds(SystemIdInfoDao_Impl.java:120)
       at androidx.work.impl.background.systemjob.SystemJobScheduler.reconcileJobs(SystemJobScheduler.java:298)
       at androidx.work.impl.utils.ForceStopRunnable.cleanUp(ForceStopRunnable.java:249)
       at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:215)
       at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:110)
       at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by uerceg** [comment]
Hi @averinuv 

Thank you for reporting. This is weird. Our SDK is not using any of the **androidx** dependencies under the hood (also no Room or SQLite). So I am not really sure right now how can this be related to our Adjust SDK.

Can you always reproduce this issue? If yes, what are the steps? Does it work if you remove Adjust SDK from your app?

**Comment by MerdanDev** [comment]
> Found the problem, it wasn't the SDK. Thanks!

####Hello averinuv, can you show detailed solution for this problem? 

I had very similar error when users update from play store. Even I backrolled to preveous version app but having this type of error again. (bfr)Thanks for your help!
