### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Adjust"

### ISSUE THREAD

**Issue by dmendoza05** [adjust/flutter_sdk#87]
Running a build on a Gitlab Runner after upgrading to `4.31.0` gives this warning: 
```
    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_5_1_d.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/5/1/d/Adjust/4.30.0/Adjust.podspec.json exists! Returning local because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "Adjust":
      In Podfile:
        adjust_sdk (from `.symlinks/plugins/adjust_sdk/ios`) was resolved to 4.31.0, which depends on
          Adjust (= 4.31.0)
    None of your spec sources contain a spec satisfying the dependency: `Adjust (= 4.31.0)`.
    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * mistyped the name or version.
     * not added the source repo that hosts the Podspec to your Podfile.
```
Already tried these solutions people recommended online (mainly from StackOverflow):

Solution 1:
```
pod deintegrate
pod install
```

Solution 2:
```
pod install --repo-update
```

Solution 3:
```
Delete the podfile.lock
Reinstantiate it by pod install
```

Solution 4:
```
flutter pub clean 
```

---- 

**flutter doctor -v**
```
[✓] Flutter (Channel stable, 3.0.5, on macOS 11.6.3 20G415 darwin-x64, locale en-US)
    • Flutter version 3.0.5 at /usr/local/flutter_2.2.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6.3 20G415 darwin-x64
[✓] HTTP Host Availability
    • All required HTTP hosts are available
• No issues found!
```

**flutter build ipa**
```
Running "flutter pub get" in [redacted]...                       2,528ms
Archiving [redacted]...
Automatically signing iOS for device deployment using specified development team in Xcode project: [redacted]
Running pod install...                                           2,143ms
CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `adjust_sdk` from `.symlinks/plugins/adjust_sdk/ios`
    -> Fetching podspec for `audio_session` from `.symlinks/plugins/audio_session/ios`
    -> Fetching podspec for `device_info_plus` from `.symlinks/plugins/device_info_plus/ios`
    -> Fetching podspec for `flutter_midi` from `.symlinks/plugins/flutter_midi/ios`
    -> Fetching podspec for `flutter_sequencer` from `.symlinks/plugins/flutter_sequencer/ios`
    -> Fetching podspec for `in_app_purchase_storekit` from `.symlinks/plugins/in_app_purchase_storekit/ios`
    -> Fetching podspec for `integration_test` from `.symlinks/plugins/integration_test/ios`
    -> Fetching podspec for `just_audio` from `.symlinks/plugins/just_audio/ios`
    -> Fetching podspec for `package_info_plus` from `.symlinks/plugins/package_info_plus/ios`
    -> Fetching podspec for `path_provider_ios` from `.symlinks/plugins/path_provider_ios/ios`
    -> Fetching podspec for `shared_preferences_ios` from `.symlinks/plugins/shared_preferences_ios/ios`
    -> Fetching podspec for `store_redirect` from `.symlinks/plugins/store_redirect/ios`
    -> Fetching podspec for `url_launcher_ios` from `.symlinks/plugins/url_launcher_ios/ios`
    -> Fetching podspec for `video_player_avfoundation` from `.symlinks/plugins/video_player_avfoundation/ios`
    -> Fetching podspec for `wakelock` from `.symlinks/plugins/wakelock/ios`
    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_5_1_d.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/5/1/d/Adjust/4.30.0/Adjust.podspec.json exists! Returning local because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "Adjust":
      In Podfile:
        adjust_sdk (from `.symlinks/plugins/adjust_sdk/ios`) was resolved to 4.31.0, which depends on
          Adjust (= 4.31.0)
    None of your spec sources contain a spec satisfying the dependency: `Adjust (= 4.31.0)`.
    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * mistyped the name or version.
     * not added the source repo that hosts the Podspec to your Podfile.
    /Users/admin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
    /Users/admin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
    /Users/admin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `tap'
    /Users/admin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
    /Users/admin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /Users/admin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /Users/admin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /Users/admin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/resolver.rb:94:in `resolve'
    /Users/admin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
    /Users/admin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/admin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/analyzer.rb:10[76]([redacted]):in `resolve_dependencies'
    /Users/admin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Users/admin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:416:in `analyze'
    /Users/admin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
    /Users/admin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/admin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
    /Users/admin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:161:in `install!'
    /Users/admin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/command/install.rb:52:in `run'
    /Users/admin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Users/admin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/lib/cocoapods/command.rb:52:in `run'
    /Users/admin/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.0/bin/pod:55:in `<top (required)>'
    /Users/admin/.rvm/rubies/ruby-2.7.2/bin/pod:23:in `load'
    /Users/admin/.rvm/rubies/ruby-2.7.2/bin/pod:23:in `<main>'
    /Users/admin/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
    /Users/admin/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update
Error running pod install
```

**Comment by uerceg** [comment]
Hi @dmendoza05 

Thanks for reporting, pretty interesting. Also some initial checks online do seem to suggest that this might not be specific pod issue, but rather to have something to do with CocoaPods behind the scenes. We didn't manage to reproduce this on our end so far. Is your CocoaPods version up to date? Can you maybe reproduce this in some dummy example app which you can send us over to check?

**Comment by dmendoza05** [comment]
Hi @uerceg

Thank you for the fast reply! I did a full reset of the `ios` directory as a last ditch try combined with clearing the dart cache and it worked. Must've been something within the runner that wasn't being cleared.

Sorry for the trouble. ✌️
